version: '3'
services:
    nginx:
        image: nginx:1.17
        ports:
            - "80:80"
        volumes:
            - "./docker-configs/nginx.conf:/etc/nginx/conf.d/default.conf"
            - ".:/app:cached"

    php:
        build:
            context: ./docker-configs/php
        volumes:
            - "./docker-configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./docker-configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
            - ".:/app:cached"
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    postgresql:
        image: postgres:11.5
        environment:
            POSTGRES_DB: ${APP_DATABASE}
            POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
        volumes:
            - "postgresdata:/var/lib/postgresql/11.5/main"
        ports:
            - "127.0.0.1:${APP_DATABASE_PORT}:5432"

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
volumes:
    postgresdata:
